
import UIKit
protocol SourceryGeneration { }

extension UIKit.UIView: SourceryGeneration {}
extension UIKit.MKTransitIncidentItemCellBackgroundView: SourceryGeneration {}
extension UIKit.MKStarRatingAndLabelView: SourceryGeneration {}
extension UIKit.MKStarRatingView: SourceryGeneration {}
extension UIKit.MKStarkCompassView: SourceryGeneration {}
extension UIKit._MKBezierPathView: SourceryGeneration {}
extension UIKit.MKActionRowItemView: SourceryGeneration {}
extension UIKit._MKCalloutBackgroundMaskView: SourceryGeneration {}
extension UIKit._MKResultView: SourceryGeneration {}
extension UIKit.MKScaleView: SourceryGeneration {}
extension UIKit._MKScaleUnitsView: SourceryGeneration {}
extension UIKit._MKSegmentView: SourceryGeneration {}
extension UIKit._MKBalloonCalloutView: SourceryGeneration {}
extension UIKit.MKUserTrackingButton: SourceryGeneration {}
extension UIKit.MKMultiPartLabel: SourceryGeneration {}
extension UIKit.MKThemeMultiPartLabel: SourceryGeneration {}
extension UIKit._MKPaddedTextAttachmentImageView: SourceryGeneration {}
extension UIKit.MKCompassButton: SourceryGeneration {}
extension UIKit.MKInfoCardLoadingView: SourceryGeneration {}
extension UIKit.MKPhotoBigAttributionView: SourceryGeneration {}
extension UIKit.MKPhotoSmallAttributionView: SourceryGeneration {}
extension UIKit._MKCalloutAccessoryWrapperView: SourceryGeneration {}
extension UIKit._MKSmallCalloutContainerView: SourceryGeneration {}
extension UIKit.MKSmallCalloutView: SourceryGeneration {}
extension UIKit._MKStackingPlaceholderView: SourceryGeneration {}
extension UIKit._MKMapLayerHostingView: SourceryGeneration {}
extension UIKit.MKBasicMapView: SourceryGeneration {}
extension UIKit._MKGradientView: SourceryGeneration {}
extension UIKit._MKPopoverEmbeddingView: SourceryGeneration {}
extension UIKit._MKZoomSliderView: SourceryGeneration {}
extension UIKit.MKAttributionLabel: SourceryGeneration {}
extension UIKit.MKExpandingLabel: SourceryGeneration {}
extension UIKit.MKPlacePhotosView: SourceryGeneration {}
extension UIKit._MKEnvironmentLabel: SourceryGeneration {}
extension UIKit.MKPlatterView: SourceryGeneration {}
extension UIKit.MKOverlayContainerView: SourceryGeneration {}
extension UIKit.MKCompassView: SourceryGeneration {}
extension UIKit.MKAnnotationContainerView: SourceryGeneration {}
extension UIKit.MKNewAnnotationContainerView: SourceryGeneration {}
extension UIKit.MKOldAnnotationContainerView: SourceryGeneration {}
extension UIKit.MKOverlayView: SourceryGeneration {}
extension UIKit.MKOverlayPathView: SourceryGeneration {}
extension UIKit.MKPolylineView: SourceryGeneration {}
extension UIKit.MKPolygonView: SourceryGeneration {}
extension UIKit.MKCircleView: SourceryGeneration {}
extension UIKit._MKStackView: SourceryGeneration {}
extension UIKit.MKPlaceSectionView: SourceryGeneration {}
extension UIKit._MKStackingViewControllerHeaderView: SourceryGeneration {}
extension UIKit._MKUIViewControllerRootView: SourceryGeneration {}
extension UIKit._MKStackingContentView: SourceryGeneration {}
extension UIKit._MKUIViewControllerClickableRootView: SourceryGeneration {}
extension UIKit._MKPlaceInlineMapContentView: SourceryGeneration {}
extension UIKit._MKPlacePoisInlineMapContentView: SourceryGeneration {}
extension UIKit.MKAnnotationView: SourceryGeneration {}
extension UIKit.MKUserLocationView: SourceryGeneration {}
extension UIKit._MKGemUserLocationView: SourceryGeneration {}
extension UIKit.MKModernUserLocationView: SourceryGeneration {}
extension UIKit.MKLabelMarkerView: SourceryGeneration {}
extension UIKit.MKPinAnnotationView: SourceryGeneration {}
extension UIKit._MKBalloonAnnotationView: SourceryGeneration {}
extension UIKit.MKMarkerAnnotationView: SourceryGeneration {}
extension UIKit.MKMapView: SourceryGeneration {}
extension UIKit.MKScrollContainerView: SourceryGeneration {}
extension UIKit._MKMapContentView: SourceryGeneration {}
extension UIKit.MKViewWithHairline: SourceryGeneration {}
extension UIKit.MKPlaceSectionItemView: SourceryGeneration {}
extension UIKit.MKPlaceSectionHeaderView: SourceryGeneration {}
extension UIKit.MKPlaceSectionRowView: SourceryGeneration {}
extension UIKit.MKPlaceTextBlockCell: SourceryGeneration {}
extension UIKit.MKPlaceReservationRowView: SourceryGeneration {}
extension UIKit.MKPlaceEncyclopedicRowView: SourceryGeneration {}
extension UIKit.MKPlaceEncyclopedicFactoidView: SourceryGeneration {}
extension UIKit.MKPlaceTextCell: SourceryGeneration {}
extension UIKit._MKPlaceDealView: SourceryGeneration {}
extension UIKit.MKPlaceInfoContactRowView: SourceryGeneration {}
extension UIKit.MKPlaceInfoBusinessMessageRowView: SourceryGeneration {}
extension UIKit.MKPlaceInfoPostalAddressRowView: SourceryGeneration {}
extension UIKit.MKPlaceInfoEmailRowView: SourceryGeneration {}
extension UIKit.MKPlaceInfoURLRowView: SourceryGeneration {}
extension UIKit.MKPlaceInfoPhoneNumberView: SourceryGeneration {}
extension UIKit.MKPlaceAttributionCell: SourceryGeneration {}
extension UIKit.MKPlaceDirectionsCell: SourceryGeneration {}
extension UIKit.MKOfficialAppView: SourceryGeneration {}
extension UIKit.MKPlaceHoursDayRow: SourceryGeneration {}
extension UIKit.MKPlaceCardActionSectionView: SourceryGeneration {}
extension UIKit._MKPlaceBusinessInfoRow: SourceryGeneration {}
extension UIKit.MKPlaceReviewsViewCell: SourceryGeneration {}
extension UIKit.SCNView: SourceryGeneration {}
extension UIKit.CNActionsView: SourceryGeneration {}
extension UIKit.CNAvatarCardActionsView: SourceryGeneration {}
extension UIKit.CNStarkNoContentBannerView: SourceryGeneration {}
extension UIKit.CNStarkContactNameView: SourceryGeneration {}
extension UIKit.CNContactGridClippingView: SourceryGeneration {}
extension UIKit.CNRepeatingGradientSeparatorView: SourceryGeneration {}
extension UIKit.CNQuickActionButton: SourceryGeneration {}
extension UIKit.CNQuickActionsView: SourceryGeneration {}
extension UIKit.CNContactListBannerView: SourceryGeneration {}
extension UIKit._CNAvatarView: SourceryGeneration {}
extension UIKit.CNAvatarCardHighlightView: SourceryGeneration {}
extension UIKit.CNActionView: SourceryGeneration {}
extension UIKit.CNContactHeaderView: SourceryGeneration {}
extension UIKit.CNContactHeaderEditView: SourceryGeneration {}
extension UIKit.CNContactHeaderDisplayView: SourceryGeneration {}
extension UIKit.CNAvatarView: SourceryGeneration {}
extension UIKit.CNContactOrbHeaderView: SourceryGeneration {}
extension UIKit.CNAvatarCardHeaderView: SourceryGeneration {}
extension UIKit.GLKView: SourceryGeneration {}
extension UIKit.NUIWidgetGridView: SourceryGeneration {}
extension UIKit.NUIWidgetGridViewEmptyCell: SourceryGeneration {}
extension UIKit.NUIContainerView: SourceryGeneration {}
extension UIKit.NUIContainerBoxView: SourceryGeneration {}
extension UIKit.NUIContainerStackView: SourceryGeneration {}
extension UIKit.NUIWidgetGridViewCell: SourceryGeneration {}
extension UIKit.NUIContainerGridView: SourceryGeneration {}
extension UIKit.MTKView: SourceryGeneration {}
extension UIKit._UIPreviewActionSheetItemView: SourceryGeneration {}
extension UIKit._UINavigationBarLargeTitleView: SourceryGeneration {}
extension UIKit._UISearchControllerView: SourceryGeneration {}
extension UIKit._UIFlippingView: SourceryGeneration {}
extension UIKit._UIPrintMessageAndSpinnerView: SourceryGeneration {}
extension UIKit._UIAlertControllerGradientView: SourceryGeneration {}
extension UIKit._UIStaticScrollBar: SourceryGeneration {}
extension UIKit._UIBackdropContentView: SourceryGeneration {}
extension UIKit._UIBackdropEffectView: SourceryGeneration {}
extension UIKit._UIWebFindOnPageHighlightBubbleView: SourceryGeneration {}
extension UIKit._UIDimmingKnockoutBackdropView: SourceryGeneration {}
extension UIKit._UIDetachedFieldEditorBackgroundView: SourceryGeneration {}
extension UIKit._UIAlertControllerView: SourceryGeneration {}
extension UIKit._UIActionSliderTrackComponentView: SourceryGeneration {}
extension UIKit._UIActionSliderKnob: SourceryGeneration {}
extension UIKit._UIStatusBar: SourceryGeneration {}
extension UIKit._UIStatusBarForegroundView: SourceryGeneration {}
extension UIKit._UITextContainerView: SourceryGeneration {}
extension UIKit._UIBadgeView: SourceryGeneration {}
extension UIKit._UIAccessDeniedView: SourceryGeneration {}
extension UIKit._UICAPackageView: SourceryGeneration {}
extension UIKit._UIShareInvitationRemoteViewControllerTintColorView: SourceryGeneration {}
extension UIKit._UIFocusFastScrollingIndexBarView: SourceryGeneration {}
extension UIKit._UIFocusFastScrollingIndexBarIndicatorView: SourceryGeneration {}
extension UIKit._UITableViewCellBadge: SourceryGeneration {}
extension UIKit._UITableViewCellBadgeNeue: SourceryGeneration {}
extension UIKit._UIRefreshControlModernReplicatorView: SourceryGeneration {}
extension UIKit._UIRefreshControlContentView: SourceryGeneration {}
extension UIKit._UIRefreshControlModernContentView: SourceryGeneration {}
extension UIKit._UIRefreshControlDefaultContentView: SourceryGeneration {}
extension UIKit._UIBarBackgroundTopCurtainView: SourceryGeneration {}
extension UIKit._UIAlertControllerTVBackgroundView: SourceryGeneration {}
extension UIKit._UITAMICAdaptorView: SourceryGeneration {}
extension UIKit._UIDebugColorBoundsView: SourceryGeneration {}
extension UIKit._UIInputViewContent: SourceryGeneration {}
extension UIKit._UIStackedImageContainerView: SourceryGeneration {}
extension UIKit._UITableViewDropAnimationContainerView: SourceryGeneration {}
extension UIKit._UIBarBackground: SourceryGeneration {}
extension UIKit._UIKBRTFingerDetectionFingerFeedbackView: SourceryGeneration {}
extension UIKit._UIKBRTFingerDetectionFingerCircleView: SourceryGeneration {}
extension UIKit._UIKBRTFingerDetectionView: SourceryGeneration {}
extension UIKit._UITableViewHeaderFooterContentView: SourceryGeneration {}
extension UIKit._UITableViewHeaderFooterViewBackground: SourceryGeneration {}
extension UIKit._UILayoutGuide: SourceryGeneration {}
extension UIKit._UIDebugAlignmentRectView: SourceryGeneration {}
extension UIKit._UIMirrorNinePatchView: SourceryGeneration {}
extension UIKit._UIStatusBarBezierView: SourceryGeneration {}
extension UIKit._UIProgressView: SourceryGeneration {}
extension UIKit._UIAlertControlleriOSActionSheetCancelBackgroundView: SourceryGeneration {}
extension UIKit._UIInterfaceActionLabelsPropertyView: SourceryGeneration {}
extension UIKit._UISizeTrackingView: SourceryGeneration {}
extension UIKit._UIShapeView: SourceryGeneration {}
extension UIKit._UITextDragCaretView: SourceryGeneration {}
extension UIKit._UIPopoverView: SourceryGeneration {}
extension UIKit._UIViewServiceDummyPopoverView: SourceryGeneration {}
extension UIKit._UIPopoverViewBackgroundComponentView: SourceryGeneration {}
extension UIKit._UIContentUnavailableView: SourceryGeneration {}
extension UIKit._UIContentUnavailableViewTV: SourceryGeneration {}
extension UIKit._UIPreviewPresentationEffectView: SourceryGeneration {}
extension UIKit._UIKBCompatInputView: SourceryGeneration {}
extension UIKit._UIBackButtonContainerView: SourceryGeneration {}
extension UIKit._UILegibilityView: SourceryGeneration {}
extension UIKit._UILegibilityLabel: SourceryGeneration {}
extension UIKit._UIAttributedStringView: SourceryGeneration {}
extension UIKit._UIPageViewControllerContentView: SourceryGeneration {}
extension UIKit._UINavigationBarTitleView: SourceryGeneration {}
extension UIKit._UIShortDefinitionView: SourceryGeneration {}
extension UIKit._UITextFieldContentView: SourceryGeneration {}
extension UIKit._UIReflectingView: SourceryGeneration {}
extension UIKit._UIReflectingGradientView: SourceryGeneration {}
extension UIKit._UIReflectingContainerView: SourceryGeneration {}
extension UIKit._UIExpandingGlyphsView: SourceryGeneration {}
extension UIKit._UIRemoteKeyboardPlaceholderView: SourceryGeneration {}
extension UIKit._UIRecentsAccessoryDefaultView: SourceryGeneration {}
extension UIKit._UIAlertControllerCarActionHighlightedBackgroundView: SourceryGeneration {}
extension UIKit._UINavigationItemView: SourceryGeneration {}
extension UIKit._UINavigationItemButtonView: SourceryGeneration {}
extension UIKit._UIGradientView: SourceryGeneration {}
extension UIKit._UIScrollViewIndexBarIndicator: SourceryGeneration {}
extension UIKit._UINavigationBarLegacyContentView: SourceryGeneration {}
extension UIKit._UIInteractiveHighlightContentView: SourceryGeneration {}
extension UIKit._UIPreviewPresentationContainerView: SourceryGeneration {}
extension UIKit._UIPreviewQuickActionView: SourceryGeneration {}
extension UIKit._UICircleProgressIndicator: SourceryGeneration {}
extension UIKit._UIBarContentView: SourceryGeneration {}
extension UIKit._UINavigationBarContentView: SourceryGeneration {}
extension UIKit._UIToolbarContentView: SourceryGeneration {}
extension UIKit._UIAnimatedAttachmentView: SourceryGeneration {}
extension UIKit._UIFloatingContentView: SourceryGeneration {}
extension UIKit._UIKBFloatingContentView: SourceryGeneration {}
extension UIKit._UIFloatingContentCornerRadiusAnimatingView: SourceryGeneration {}
extension UIKit._UIFloatingContentCornerRadiusAnimatingScreenScaleInheritingView: SourceryGeneration {}
extension UIKit._UIFloatingContentTransformView: SourceryGeneration {}
extension UIKit._UISearchBarContainerView: SourceryGeneration {}
extension UIKit._UINavigationBarModernPromptView: SourceryGeneration {}
extension UIKit._UIStackedImageLayerWrappingView: SourceryGeneration {}
extension UIKit._UIStackedImageLayerDelegate: SourceryGeneration {}
extension UIKit._UIStatusBarSignalView: SourceryGeneration {}
extension UIKit._UIStatusBarCellularSignalView: SourceryGeneration {}
extension UIKit._UIStatusBarWifiSignalView: SourceryGeneration {}
extension UIKit._UIUCBKBSelectionBackground: SourceryGeneration {}
extension UIKit._UIStatusBarLockItemPadlockView: SourceryGeneration {}
extension UIKit._UINavigationControllerPalette: SourceryGeneration {}
extension UIKit._UINavigationControllerManagedSearchPalette: SourceryGeneration {}
extension UIKit._UICircleProgressView: SourceryGeneration {}
extension UIKit._UIDragBadge: SourceryGeneration {}
extension UIKit._UINavBarPrompt: SourceryGeneration {}
extension UIKit._UIAlertControllerActionView: SourceryGeneration {}
extension UIKit._UIPreviewActionSheetTitleView: SourceryGeneration {}
extension UIKit._UIAlertControllerCarBackgroundView: SourceryGeneration {}
extension UIKit._UIReplicantView: SourceryGeneration {}
extension UIKit._UIVisualEffectSubview: SourceryGeneration {}
extension UIKit._UIVisualEffectContentView: SourceryGeneration {}
extension UIKit._UIVisualEffectBackdropView: SourceryGeneration {}
extension UIKit._UILayerHostView: SourceryGeneration {}
extension UIKit._UIRemoteView: SourceryGeneration {}
extension UIKit._UITextEffectsRemoteView: SourceryGeneration {}
extension UIKit._UITableViewCellEditControlMinusView: SourceryGeneration {}
extension UIKit._UIGlintyStringView: SourceryGeneration {}
extension UIKit._UIGlintyGradientView: SourceryGeneration {}
extension UIKit._UIGlintyShapeView: SourceryGeneration {}
extension UIKit._UITableViewSeparatorView: SourceryGeneration {}
extension UIKit._UIAlertControllerTextFieldView: SourceryGeneration {}
extension UIKit._UIStatusBarLockView: SourceryGeneration {}
extension UIKit._UIButtonMaskAnimationView: SourceryGeneration {}
extension UIKit._UIButtonContentCenteringSpacer: SourceryGeneration {}
extension UIKit._UITableViewCellSeparatorView: SourceryGeneration {}
extension UIKit._UIPortalView: SourceryGeneration {}
extension UIKit._UIDynamicCaretAlternatives: SourceryGeneration {}
extension UIKit._UIDynamicCaretInput: SourceryGeneration {}
extension UIKit._UIDynamicCaretDot: SourceryGeneration {}
extension UIKit._UIAlertControlleriOSActionSheetActionHighlightedBackgroundView: SourceryGeneration {}
extension UIKit._UIKeyboardLayoutAlignmentView: SourceryGeneration {}
extension UIKit._UIHighlightView: SourceryGeneration {}
extension UIKit._UIPlatterShadowView: SourceryGeneration {}
extension UIKit._UIInterfaceActionSeparatableSequenceView: SourceryGeneration {}
extension UIKit._UIDragSetDownAnimationItemComponentView: SourceryGeneration {}
extension UIKit._UIKBRTTouchDrifingFingerCircleView: SourceryGeneration {}
extension UIKit._UIDocumentPickerRemoteViewControllerTintColorView: SourceryGeneration {}
extension UIKit._UIInterfaceActionBlankSeparatorView: SourceryGeneration {}
extension UIKit._UIBlendingHighlightView: SourceryGeneration {}
extension UIKit._UIInterfaceActionBlendingSeparatorView: SourceryGeneration {}
extension UIKit._UIInterfaceActionItemSeparatorView_CarPlay: SourceryGeneration {}
extension UIKit._UIInterfaceActionSectionSeparatorView_iOS: SourceryGeneration {}
extension UIKit._UIInterfaceActionItemSeparatorView_iOS: SourceryGeneration {}
extension UIKit._UIRemoveControlWhiteView: SourceryGeneration {}
extension UIKit._UIPlatterView: SourceryGeneration {}
extension UIKit._UIImageViewOverlayView: SourceryGeneration {}
extension UIKit._UIFloatingShadowView: SourceryGeneration {}
extension UIKit._UINavigationControllerPaletteClippingView: SourceryGeneration {}
extension UIKit._UIStatusBarActivityView: SourceryGeneration {}
extension UIKit._UIStatusBarRoundedCornerView: SourceryGeneration {}
extension UIKit._UIStatusBarBackgroundActivityView: SourceryGeneration {}
extension UIKit._UIScrollViewGradientMaskView: SourceryGeneration {}
extension UIKit._UIGroupTableViewCellBackground_TV: SourceryGeneration {}
extension UIKit._UIBatteryView: SourceryGeneration {}
extension UIKit._UIPreviewActionSheetView: SourceryGeneration {}
extension UIKit._UIParallaxDimmingView: SourceryGeneration {}
extension UIKit._UIPickerWheelView: SourceryGeneration {}
extension UIKit._UIPickerViewSelectionBar: SourceryGeneration {}
extension UIKit._UIOnePartImageView: SourceryGeneration {}
extension UIKit._UIPickerViewTopFrame: SourceryGeneration {}
extension UIKit._UIPreviewPresentationPlatterView: SourceryGeneration {}
extension UIKit.DOCDocumentManagerDimmingView: SourceryGeneration {}
extension UIKit.DOCPromptView: SourceryGeneration {}
extension UIKit.DOCViewServiceErrorView: SourceryGeneration {}
extension UIKit.DOCTagChainView: SourceryGeneration {}
extension UIKit.DOCRemoteBarButtonTrackingView: SourceryGeneration {}
extension UIKit._UIGroupedBar: SourceryGeneration {}
extension UIKit.UIKeyboardAssistantBar: SourceryGeneration {}
extension UIKit.UIInterfaceActionGroupView: SourceryGeneration {}
extension UIKit._UIAlertControllerInterfaceActionGroupView: SourceryGeneration {}
extension UIKit.UIActionSheetiOSDismissActionView: SourceryGeneration {}
extension UIKit.UIPrinterSetupDisplayPINView: SourceryGeneration {}
extension UIKit.UIPrinterSetupConnectingView: SourceryGeneration {}
extension UIKit.UITextFieldAtomBackgroundView: SourceryGeneration {}
extension UIKit.UITextFieldBorderView: SourceryGeneration {}
extension UIKit.UIInputSwitcherTableCellSegmentView: SourceryGeneration {}
extension UIKit.UIInputSwitcherTableCellBackgroundView: SourceryGeneration {}
extension UIKit.UIMorphingLabel: SourceryGeneration {}
extension UIKit.UIWebPlaybackTargetPicker: SourceryGeneration {}
extension UIKit.UITableViewBackgroundView: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateInlineFloatingView: SourceryGeneration {}
extension UIKit.UIKeyboardCandidatePageControl: SourceryGeneration {}
extension UIKit.UIInputSetHostView: SourceryGeneration {}
extension UIKit.UIInputSetContainerView: SourceryGeneration {}
extension UIKit.UITextAttachmentView: SourceryGeneration {}
extension UIKit.UIAccessibilityHUDView: SourceryGeneration {}
extension UIKit.UIInputSwitcherSelectionExtraView: SourceryGeneration {}
extension UIKit.UIInputSwitcherShadowView: SourceryGeneration {}
extension UIKit.UIPanelWrapperView: SourceryGeneration {}
extension UIKit.UIDebuggingZoomLineView: SourceryGeneration {}
extension UIKit.UITableViewHeaderFooterView: SourceryGeneration {}
extension UIKit.MKTransitIncidentFooterView: SourceryGeneration {}
extension UIKit.UITableViewCellDeleteConfirmationView: SourceryGeneration {}
extension UIKit.UIPanelBorderView: SourceryGeneration {}
extension UIKit.UIPanelBorderReplicatingView: SourceryGeneration {}
extension UIKit.UIURLDragPreviewView: SourceryGeneration {}
extension UIKit.UICollectionViewControllerWrapperView: SourceryGeneration {}
extension UIKit.UIPickerColumnView: SourceryGeneration {}
extension UIKit.UISwipeActionPullView: SourceryGeneration {}
extension UIKit.UIPopoverBackgroundView: SourceryGeneration {}
extension UIKit.MKCalloutBackgroundView: SourceryGeneration {}
extension UIKit._UIViewServiceDummyPopoverBackgroundView: SourceryGeneration {}
extension UIKit._UIPopoverSlidingChromeView: SourceryGeneration {}
extension UIKit._UIPopoverStandardChromeView: SourceryGeneration {}
extension UIKit.UIActivityViewPopoverBackgroundView: SourceryGeneration {}
extension UIKit.UIKeyboardMenuView: SourceryGeneration {}
extension UIKit.UIKeyboardDictationMenu: SourceryGeneration {}
extension UIKit.UIKeyboardSplitControlMenu: SourceryGeneration {}
extension UIKit.UIInputSwitcherView: SourceryGeneration {}
extension UIKit.UIDocumentPasswordView: SourceryGeneration {}
extension UIKit.UIWebOverflowContentView: SourceryGeneration {}
extension UIKit.UIWebPDFLabelView: SourceryGeneration {}
extension UIKit.UIDictationLandingView: SourceryGeneration {}
extension UIKit.UIDebuggingZoomLoupeView: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateSortControl: SourceryGeneration {}
extension UIKit.UIDictationView: SourceryGeneration {}
extension UIKit.UIDictationPopUpView: SourceryGeneration {}
extension UIKit.UIDictationLayoutView: SourceryGeneration {}
extension UIKit.UIDictationSplitLayoutView: SourceryGeneration {}
extension UIKit.UIDictationATVLinearView: SourceryGeneration {}
extension UIKit.UIDictationFloatingStarkView: SourceryGeneration {}
extension UIKit.UIKeyboardDicationBackground: SourceryGeneration {}
extension UIKit.UIKeyboardDicationBackgroundGradientView: SourceryGeneration {}
extension UIKit.UIWebPDFView: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateGrid: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateGridHeader: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateBarShadow: SourceryGeneration {}
extension UIKit.UIDatePickerWeekMonthDayView: SourceryGeneration {}
extension UIKit.UIDatePickerContentView: SourceryGeneration {}
extension UIKit.UIActionSheet: SourceryGeneration {}
extension UIKit.UIStatusBarCorners: SourceryGeneration {}
extension UIKit.UIPrintingMessageView: SourceryGeneration {}
extension UIKit.UIPrinterSearchingView: SourceryGeneration {}
extension UIKit.UIPrinterAccessoryView: SourceryGeneration {}
extension UIKit.UIKeyboardDockView: SourceryGeneration {}
extension UIKit.UISnapshotView: SourceryGeneration {}
extension UIKit.UIInputView: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateView: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateView_Floating: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateView_iPad: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateView_iPhone: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateView_iPhone_Floating: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateView_iPhone_Bar_ExtendDown: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateView_iPhone_Bar: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateView_iPhone_Bar_ExtendHalfwayUp: SourceryGeneration {}
extension UIKit.UIWebFormAccessory: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateBar: SourceryGeneration {}
extension UIKit.UIPeripheralHostView: SourceryGeneration {}
extension UIKit.UIKeyboardCornerView: SourceryGeneration {}
extension UIKit.SupplyLevelView: SourceryGeneration {}
extension UIKit.UIDebuggingInformationValueView: SourceryGeneration {}
extension UIKit.UIDebuggingInformationValueViewNumber: SourceryGeneration {}
extension UIKit.UIKeyCommandDiscoverabilityHUDDescriptionView: SourceryGeneration {}
extension UIKit.UIDropShadowView: SourceryGeneration {}
extension UIKit.UIStatusBarForegroundView: SourceryGeneration {}
extension UIKit.UIStatusBarBackgroundView: SourceryGeneration {}
extension UIKit.UITableViewCellContentView: SourceryGeneration {}
extension UIKit.UIKBHandwritingStrokeView: SourceryGeneration {}
extension UIKit.UIStackView: SourceryGeneration {}
extension UIKit._UIButtonBarStackView: SourceryGeneration {}
extension UIKit.UISwipeActionDeleteScanlineView: SourceryGeneration {}
extension UIKit.UITableViewIndexOverlaySelectionView: SourceryGeneration {}
extension UIKit.UIKeyCommandDiscoverabilityHUDColumnView: SourceryGeneration {}
extension UIKit.UIWebDragDotView: SourceryGeneration {}
extension UIKit.UIWebTextRangeView: SourceryGeneration {}
extension UIKit.UIWebSelectionOutline: SourceryGeneration {}
extension UIKit.UIWebSelectionHandle: SourceryGeneration {}
extension UIKit.UIWebSelectionView: SourceryGeneration {}
extension UIKit.UIWKSelectionView: SourceryGeneration {}
extension UIKit.UITextContentView: SourceryGeneration {}
extension UIKit.UITextMagnifier: SourceryGeneration {}
extension UIKit.UITextMagnifierRanged: SourceryGeneration {}
extension UIKit.UITextMagnifierCaret: SourceryGeneration {}
extension UIKit.UITextMagnifierCommonRenderer: SourceryGeneration {}
extension UIKit.UITextMagnifierRangedRenderer: SourceryGeneration {}
extension UIKit.UITextMagnifierCaretRenderer: SourceryGeneration {}
extension UIKit.UIInterfaceActionRepresentationView: SourceryGeneration {}
extension UIKit._UIInterfaceActionCustomViewRepresentationView: SourceryGeneration {}
extension UIKit._UIInterfaceActionSystemRepresentationView: SourceryGeneration {}
extension UIKit.UICalloutBar: SourceryGeneration {}
extension UIKit.UICalloutBarBackground: SourceryGeneration {}
extension UIKit.UISelectionGrabber: SourceryGeneration {}
extension UIKit.UISelectionGrabberDot: SourceryGeneration {}
extension UIKit.UIKBThemedView: SourceryGeneration {}
extension UIKit.UITextRangeView: SourceryGeneration {}
extension UIKit.UITextSelectionView: SourceryGeneration {}
extension UIKit.UISearchDisplayControllerContainerView: SourceryGeneration {}
extension UIKit.UIGroupTableViewCellBackground: SourceryGeneration {}
extension UIKit.UIVisualEffectView: SourceryGeneration {}
extension UIKit._UIInteractiveHighlightBackgroundEffectView: SourceryGeneration {}
extension UIKit.DOCBarBackgroundView: SourceryGeneration {}
extension UIKit.UIKBDimmingView: SourceryGeneration {}
extension UIKit.UIKBSplitImageView: SourceryGeneration {}
extension UIKit.UIKBKeyplaneView: SourceryGeneration {}
extension UIKit.UIKBBackgroundView: SourceryGeneration {}
extension UIKit.UISpringBoardHostedView: SourceryGeneration {}
extension UIKit.UIPickerContentView: SourceryGeneration {}
extension UIKit.UIDOMHTMLOptionPickerCell: SourceryGeneration {}
extension UIKit.UIDOMHTMLOptGroupCell: SourceryGeneration {}
extension UIKit.UINavigationTransitionView: SourceryGeneration {}
extension UIKit.UIMovieScrubberEditingView: SourceryGeneration {}
extension UIKit.UIMovieScrubberTrackOverlayView: SourceryGeneration {}
extension UIKit.UIMovieScrubberTrackView: SourceryGeneration {}
extension UIKit.UIKBFocusVCView: SourceryGeneration {}
extension UIKit.UIDimmingView: SourceryGeneration {}
extension UIKit._UIScrollsToTopInitiatorView: SourceryGeneration {}
extension UIKit.UIClassicStatusBarView: SourceryGeneration {}
extension UIKit.UIStatusBar_Base: SourceryGeneration {}
extension UIKit.UIStatusBar: SourceryGeneration {}
extension UIKit.UIStatusBar_Modern: SourceryGeneration {}
extension UIKit.UITableViewCellContentMirror: SourceryGeneration {}
extension UIKit.UIKeyboardPredictionView: SourceryGeneration {}
extension UIKit.UIKeyboardPredictionBarGrabber: SourceryGeneration {}
extension UIKit.UIKeyboardPredictionCell: SourceryGeneration {}
extension UIKit.UIKeyboardEmojiScrubBarView: SourceryGeneration {}
extension UIKit.UIKeyboardSplitTransitionView: SourceryGeneration {}
extension UIKit.UIKeyboardSliceTransitionView: SourceryGeneration {}
extension UIKit.UIKeyboardFlipTransitionView: SourceryGeneration {}
extension UIKit.UIProgressView: SourceryGeneration {}
extension UIKit.UISearchBar: SourceryGeneration {}
extension UIKit.DOCSearchBar: SourceryGeneration {}
extension UIKit.UITabBar: SourceryGeneration {}
extension UIKit.UITabBarCustomizeView: SourceryGeneration {}
extension UIKit.UISplitAndMaskView: SourceryGeneration {}
extension UIKit.UILayoutContainerView: SourceryGeneration {}
extension UIKit.UITableViewCellSelectedBackground: SourceryGeneration {}
extension UIKit.UIWebView: SourceryGeneration {}
extension UIKit.UIAlertView: SourceryGeneration {}
extension UIKit._UIUserNotificationAlertView: SourceryGeneration {}
extension UIKit.UITableViewCell: SourceryGeneration {}
extension UIKit.MKNearestStationLoadingCell: SourceryGeneration {}
extension UIKit.MKNearestStationCell: SourceryGeneration {}
extension UIKit.MKNearestStationErrorCell: SourceryGeneration {}
extension UIKit.MKTableViewCell: SourceryGeneration {}
extension UIKit.MKTransitIncidentSummaryCell: SourceryGeneration {}
extension UIKit.MKTransitIncidentDetailCell: SourceryGeneration {}
extension UIKit.MKPlaceViewNearbyAppsCell: SourceryGeneration {}
extension UIKit.MKCustomSeparatorTableViewCell: SourceryGeneration {}
extension UIKit.MKTransitDeparturesSectionHeaderView: SourceryGeneration {}
extension UIKit.MKTransitDeparturesCell: SourceryGeneration {}
extension UIKit._MKTransitConnectionCell: SourceryGeneration {}
extension UIKit.MKTransitLoadingTableViewCell: SourceryGeneration {}
extension UIKit.MKTransitItemIncidentCell: SourceryGeneration {}
extension UIKit.MKTransitSystemCell: SourceryGeneration {}
extension UIKit.MKTransitAttributionSummaryCell: SourceryGeneration {}
extension UIKit.MKTransitMessageCell: SourceryGeneration {}
extension UIKit.CNUIPeopleCell: SourceryGeneration {}
extension UIKit.CNPickerItemCell: SourceryGeneration {}
extension UIKit.CNAccountsAndGroupsTableViewCell: SourceryGeneration {}
extension UIKit.CNAvatarCardActionCell: SourceryGeneration {}
extension UIKit.CNAvatarCardContactCell: SourceryGeneration {}
extension UIKit.CNContactListTableViewCell: SourceryGeneration {}
extension UIKit.CNUINavigationListViewCell: SourceryGeneration {}
extension UIKit.CNUIDetailNavigationListViewCell: SourceryGeneration {}
extension UIKit.CNAddressComponentTextFieldCell: SourceryGeneration {}
extension UIKit.CNAddressComponentSplitTextFieldCell: SourceryGeneration {}
extension UIKit.CNContactCell: SourceryGeneration {}
extension UIKit.CNPropertyNameCell: SourceryGeneration {}
extension UIKit.ABPostalNameContactEditingCell: SourceryGeneration {}
extension UIKit.CNStarkFaceTimeCell: SourceryGeneration {}
extension UIKit.CNLabeledCell: SourceryGeneration {}
extension UIKit.CNPropertyCell: SourceryGeneration {}
extension UIKit.CNPropertyNoteCell: SourceryGeneration {}
extension UIKit.CNPropertyEditingCell: SourceryGeneration {}
extension UIKit.CNPropertyPostalAddressEditingCell: SourceryGeneration {}
extension UIKit.CNPropertySimpleEditingCell: SourceryGeneration {}
extension UIKit.CNPropertyURLAddressEditingCell: SourceryGeneration {}
extension UIKit.CNPropertySocialProfileEditingCell: SourceryGeneration {}
extension UIKit.CNPropertyRelatedNameEditingCell: SourceryGeneration {}
extension UIKit.CNPropertyPhoneNumberEditingCell: SourceryGeneration {}
extension UIKit.CNPropertyInstantMessageEditingCell: SourceryGeneration {}
extension UIKit.CNPropertyDateEditingCell: SourceryGeneration {}
extension UIKit.CNPropertySimpleCell: SourceryGeneration {}
extension UIKit.CNPropertySimpleTransportCell: SourceryGeneration {}
extension UIKit.CNPropertyPostalAddressCell: SourceryGeneration {}
extension UIKit.CNStarkContactAddressPropertyCell: SourceryGeneration {}
extension UIKit.CNPropertyPhoneNumberCell: SourceryGeneration {}
extension UIKit.CNStarkContactPropertyCell: SourceryGeneration {}
extension UIKit.CNPropertyEmailAddressCell: SourceryGeneration {}
extension UIKit.CNPropertyIntentActionableCell: SourceryGeneration {}
extension UIKit.CNPropertyAlertCell: SourceryGeneration {}
extension UIKit.CNPropertyAlertEditingCell: SourceryGeneration {}
extension UIKit.CNPropertyPlaceholderCell: SourceryGeneration {}
extension UIKit.CNLinkedCardsPlaceholderCell: SourceryGeneration {}
extension UIKit.CNLinkedCardsCell: SourceryGeneration {}
extension UIKit.CNLinkedCardsEditingCell: SourceryGeneration {}
extension UIKit.CNFaceTimeCell: SourceryGeneration {}
extension UIKit.CNContactActionSplitCell: SourceryGeneration {}
extension UIKit.CNContactActionCell: SourceryGeneration {}
extension UIKit._UISwipeToDeletePlaceholderCell: SourceryGeneration {}
extension UIKit.UIInputSwitcherTableCell: SourceryGeneration {}
extension UIKit.UIInputSwitcherSegmentedTableCell: SourceryGeneration {}
extension UIKit.UIDebuggingIvarTableViewCell: SourceryGeneration {}
extension UIKit.UIPickerTableViewCell: SourceryGeneration {}
extension UIKit.UIPickerTableViewTitledCell: SourceryGeneration {}
extension UIKit.UIPickerTableViewWrapperCell: SourceryGeneration {}
extension UIKit.UIRecentInputTableCell: SourceryGeneration {}
extension UIKit.UIPrinterTableViewCell: SourceryGeneration {}
extension UIKit.UIDebuggingInformationValueTableViewCell: SourceryGeneration {}
extension UIKit.UIMainPrinterUtilityCell: SourceryGeneration {}
extension UIKit.UIDebuggingColorAuditTableViewCell: SourceryGeneration {}
extension UIKit.UIKeyboardEmojiSplitCategoryCell: SourceryGeneration {}
extension UIKit.UITableViewCollectionCell: SourceryGeneration {}
extension UIKit.UIWebTiledView: SourceryGeneration {}
extension UIKit.UIWebDocumentView: SourceryGeneration {}
extension UIKit.UIWebBrowserView: SourceryGeneration {}
extension UIKit.UITextFieldBackgroundView: SourceryGeneration {}
extension UIKit._UITextFieldPasscodeCutoutBackground: SourceryGeneration {}
extension UIKit.UITextFieldRoundedRectBackgroundView: SourceryGeneration {}
extension UIKit.UIPasscodeField: SourceryGeneration {}
extension UIKit.UIDefaultKeyboardInput: SourceryGeneration {}
extension UIKit.UIKeyboardLayout: SourceryGeneration {}
extension UIKit.UIKeyboardLayoutDictation: SourceryGeneration {}
extension UIKit.UIKeyboardLayoutStar: SourceryGeneration {}
extension UIKit.UIKeyboardLayoutCursor: SourceryGeneration {}
extension UIKit.UIAutocorrectInlinePrompt: SourceryGeneration {}
extension UIKit.UIAutocorrectTextView: SourceryGeneration {}
extension UIKit.UIAutocorrectShadowView: SourceryGeneration {}
extension UIKit.UIKeyboard: SourceryGeneration {}
extension UIKit.UIKeyboardAutomatic: SourceryGeneration {}
extension UIKit.UIKeyboardImpl: SourceryGeneration {}
extension UIKit.UICheckeredPatternView: SourceryGeneration {}
extension UIKit.UIProgressHUD: SourceryGeneration {}
extension UIKit.UIShadowView: SourceryGeneration {}
extension UIKit.UIKBInputBackdropView: SourceryGeneration {}
extension UIKit._UIBackdropView: SourceryGeneration {}
extension UIKit.UIKBBackdropView: SourceryGeneration {}
extension UIKit.UIToolbar: SourceryGeneration {}
extension UIKit.UIRemoveControl: SourceryGeneration {}
extension UIKit._UITableViewCellRemoveControl: SourceryGeneration {}
extension UIKit.UIInsertControl: SourceryGeneration {}
extension UIKit.UIKeyCommandDiscoverabilityHUDView: SourceryGeneration {}
extension UIKit.UICollectionReusableView: SourceryGeneration {}
extension UIKit._UICollectionSnapshotView: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateGridHeaderContainerView: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateGridOverlayBackgroundView: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateFloatingArrowView: SourceryGeneration {}
extension UIKit.UICollectionViewTableHeaderFooterView: SourceryGeneration {}
extension UIKit.UIKeyboardEmojiSectionHeader: SourceryGeneration {}
extension UIKit.UICollectionViewTableSeparatorView: SourceryGeneration {}
extension UIKit.UIKeyboardCandidatePocketShadow: SourceryGeneration {}
extension UIKit.UICollectionViewCell: SourceryGeneration {}
extension UIKit.MKVenuesBrowseCollectionViewCell: SourceryGeneration {}
extension UIKit.MKPlaceViewNearbyAppCollectionViewCell: SourceryGeneration {}
extension UIKit.CNUIPeopleGroupCell: SourceryGeneration {}
extension UIKit.CNContactGridCell: SourceryGeneration {}
extension UIKit.CNQuickActionCell: SourceryGeneration {}
extension UIKit._UIActivityGroupActivityCell: SourceryGeneration {}
extension UIKit._UIPrintPreviewPageCell: SourceryGeneration {}
extension UIKit._UIAlertControllerTextFieldViewCollectionCell: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateBarCell: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateBarCell_SecondaryCandidate: SourceryGeneration {}
extension UIKit.UIKeyboardEmojiCollectionViewCell: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateGridCell: SourceryGeneration {}
extension UIKit.UITableViewIndexOverlaySelectionViewCollectionViewCell: SourceryGeneration {}
extension UIKit.UIKBRecentInputCell: SourceryGeneration {}
extension UIKit.UIKBHandwritingCandidateViewCell: SourceryGeneration {}
extension UIKit.UIKBLinearCandidateViewCell: SourceryGeneration {}
extension UIKit.UICollectionViewTableCell: SourceryGeneration {}
extension UIKit.UIKeyCommandDiscoverabilityHUDViewCell: SourceryGeneration {}
extension UIKit.UILabel: SourceryGeneration {}
extension UIKit.MKDebugLocationConsole: SourceryGeneration {}
extension UIKit._MKUILabel: SourceryGeneration {}
extension UIKit.MKTransitInfoLabelView: SourceryGeneration {}
extension UIKit._UITableViewHeaderFooterViewLabel: SourceryGeneration {}
extension UIKit._UIActivityGroupActivityCellTitleLabel: SourceryGeneration {}
extension UIKit._UIStatusBarStringView: SourceryGeneration {}
extension UIKit.UITabBarButtonLabel: SourceryGeneration {}
extension UIKit.UITableViewLabel: SourceryGeneration {}
extension UIKit.UITableViewCountView: SourceryGeneration {}
extension UIKit.UITextFieldLabel: SourceryGeneration {}
extension UIKit._UIBaselineLayoutStrut: SourceryGeneration {}
extension UIKit.UITextFieldCenteredLabel: SourceryGeneration {}
extension UIKit.UISearchBarTextFieldLabel: SourceryGeneration {}
extension UIKit.UIButtonLabel: SourceryGeneration {}
extension UIKit.UIDateLabel: SourceryGeneration {}
extension UIKit.UITextLabel: SourceryGeneration {}
extension UIKit.UISegmentLabel: SourceryGeneration {}
extension UIKit.UIActivityIndicatorView: SourceryGeneration {}
extension UIKit._UIStatusBarActivityIndicator: SourceryGeneration {}
extension UIKit.UIProgressIndicator: SourceryGeneration {}
extension UIKit.UIImageView: SourceryGeneration {}
extension UIKit.MKInfoCardTintColoringImageView: SourceryGeneration {}
extension UIKit._MKPlatterImageViewNoAutoLayout: SourceryGeneration {}
extension UIKit.MKArtworkImageView: SourceryGeneration {}
extension UIKit._UIStatusBarImageView: SourceryGeneration {}
extension UIKit._UIBarBackgroundCustomImageContainer: SourceryGeneration {}
extension UIKit._UITextAttachmentImageView: SourceryGeneration {}
extension UIKit._UITextAttachmentPlaceholderView: SourceryGeneration {}
extension UIKit._UILegibilityImageView: SourceryGeneration {}
extension UIKit._UIVisualEffectImageView: SourceryGeneration {}
extension UIKit._UISearchBarScopeBarBackground: SourceryGeneration {}
extension UIKit._UISearchBarShadowView: SourceryGeneration {}
extension UIKit._UIDynamicCaretHelpLabel: SourceryGeneration {}
extension UIKit._UIDynamicCaretNoContentView: SourceryGeneration {}
extension UIKit._UITextFieldRoundedRectBackgroundViewNeue: SourceryGeneration {}
extension UIKit._UISearchBarSearchFieldBackgroundView: SourceryGeneration {}
extension UIKit._UISegmentedControlBackgroundView: SourceryGeneration {}
extension UIKit._UIInterfaceActionImagePropertyView: SourceryGeneration {}
extension UIKit.UIKBCursorSelection: SourceryGeneration {}
extension UIKit.UITabBarSwappableImageView: SourceryGeneration {}
extension UIKit.UINavigationBarBackIndicatorView: SourceryGeneration {}
extension UIKit.UIMovieScrubberThumbnailView: SourceryGeneration {}
extension UIKit.UISwappableImageView: SourceryGeneration {}
extension UIKit._UIBarBackgroundImageView: SourceryGeneration {}
extension UIKit.UISearchBarBackground: SourceryGeneration {}
extension UIKit.UIDynamicCaret: SourceryGeneration {}
extension UIKit.UISegment: SourceryGeneration {}
extension UIKit.UIViewControllerWrapperView: SourceryGeneration {}
extension UIKit.UIStatusBarItemView: SourceryGeneration {}
extension UIKit.UIStatusBarMapsCompassItemView: SourceryGeneration {}
extension UIKit.UIStatusBarLiquidDetectionItemView: SourceryGeneration {}
extension UIKit.UIStatusBarElectronicTollCollectionItemView: SourceryGeneration {}
extension UIKit.UIStatusBarLocationItemView: SourceryGeneration {}
extension UIKit.UIStatusBarDoubleHeightItemView: SourceryGeneration {}
extension UIKit.UIStatusBarNotChargingItemView: SourceryGeneration {}
extension UIKit.UIStatusBarThermalColorItemView: SourceryGeneration {}
extension UIKit.UIStatusBarActivityItemView: SourceryGeneration {}
extension UIKit.UIStatusBarBluetoothBatteryItemView: SourceryGeneration {}
extension UIKit.UIStatusBarBluetoothItemView: SourceryGeneration {}
extension UIKit.UIStatusBarBatteryPercentItemView: SourceryGeneration {}
extension UIKit.UIStatusBarBatteryItemView: SourceryGeneration {}
extension UIKit.UIStatusBarServiceItemView: SourceryGeneration {}
extension UIKit.UIStatusBarTimeItemView: SourceryGeneration {}
extension UIKit.UIStatusBarDataNetworkItemView: SourceryGeneration {}
extension UIKit.UIStatusBarSignalStrengthItemView: SourceryGeneration {}
extension UIKit.UIStatusBarPersonNameItemView: SourceryGeneration {}
extension UIKit.UIStatusBarLockItemView: SourceryGeneration {}
extension UIKit.UIStatusBarSystemNavigationItemView: SourceryGeneration {}
extension UIKit.UIStatusBarBreadcrumbItemView: SourceryGeneration {}
extension UIKit.UIStatusBarOpenInSafariItemView: SourceryGeneration {}
extension UIKit.UIStatusBarCarPlayDockItemView: SourceryGeneration {}
extension UIKit.UIStatusBarIndicatorItemView: SourceryGeneration {}
extension UIKit.UIStatusBarQuietModeItemView: SourceryGeneration {}
extension UIKit.UIStatusBarAirplaneModeItemView: SourceryGeneration {}
extension UIKit.UIStatusBarCarPlayItemView: SourceryGeneration {}
extension UIKit.UIStatusBarStudentItemView: SourceryGeneration {}
extension UIKit.UIStatusBarTetheringItemView: SourceryGeneration {}
extension UIKit.UIStatusBarButtonActionItemView: SourceryGeneration {}
extension UIKit.UIStatusBarCarPlayTimeItemView: SourceryGeneration {}
extension UIKit.UIStatusBarHomeItemView: SourceryGeneration {}
extension UIKit.UIStatusBarAppIconItemView: SourceryGeneration {}
extension UIKit.UIStatusBarNavigationItemView: SourceryGeneration {}
extension UIKit.UIStatusBarReturnToCallItemView: SourceryGeneration {}
extension UIKit.UIStatusBarRadarItemView: SourceryGeneration {}
extension UIKit.UITransitionView: SourceryGeneration {}
extension UIKit.UINavigationBar: SourceryGeneration {}
extension UIKit.UISwitchVisualElement: SourceryGeneration {}
extension UIKit.UISwitchiOS6VisualElement: SourceryGeneration {}
extension UIKit.UISwitchModernVisualElement: SourceryGeneration {}
extension UIKit.UISwitchCarPlayVisualElement: SourceryGeneration {}
extension UIKit.UITableViewIndexOverlayIndicatorView: SourceryGeneration {}
extension UIKit.UIWindow: SourceryGeneration {}
extension UIKit._SCNSnapshotWindow: SourceryGeneration {}
extension UIKit._UIKeyCommandDiscoverabilityHUDWindow: SourceryGeneration {}
extension UIKit._UIHostedWindow: SourceryGeneration {}
extension UIKit._UISecureHostedWindow: SourceryGeneration {}
extension UIKit._UIPreviewInteractionTransitionWindow: SourceryGeneration {}
extension UIKit._UIInteractiveHighlightEffectWindow: SourceryGeneration {}
extension UIKit._UIRootWindow: SourceryGeneration {}
extension UIKit._UIFeedbackVisualizerWindow: SourceryGeneration {}
extension UIKit._UISnapshotWindow: SourceryGeneration {}
extension UIKit._UIScreenEdgePanRecognizerAnalysisWindow: SourceryGeneration {}
extension UIKit._UIDragSetDownAnimationWindow: SourceryGeneration {}
extension UIKit._UIBackgroundHitTestWindow: SourceryGeneration {}
extension UIKit.UIDebuggingInformationOverlay: SourceryGeneration {}
extension UIKit.UIDictationPresenterWindow: SourceryGeneration {}
extension UIKit.UIPrintPanelWindow: SourceryGeneration {}
extension UIKit.UIStatusBarWindow: SourceryGeneration {}
extension UIKit.UIClassicWindow: SourceryGeneration {}
extension UIKit.UIStatusBarAdornmentWindow: SourceryGeneration {}
extension UIKit.UISoftwareDimmingWindow: SourceryGeneration {}
extension UIKit.UIPrinterPickerWindow: SourceryGeneration {}
extension UIKit.UIApplicationRotationFollowingWindow: SourceryGeneration {}
extension UIKit._UIAlertControllerShimPresenterWindow: SourceryGeneration {}
extension UIKit._UIFallbackPresentationWindow: SourceryGeneration {}
extension UIKit.UIAutoRotatingWindow: SourceryGeneration {}
extension UIKit.UITextEffectsWindow: SourceryGeneration {}
extension UIKit.UIRemoteKeyboardWindow: SourceryGeneration {}
extension UIKit.UIRemoteKeyboardWindowHosted: SourceryGeneration {}
extension UIKit.UITextEffectsWindowHosted: SourceryGeneration {}
extension UIKit.UITextEffectsWindowNoAbove: SourceryGeneration {}
extension UIKit.UIApplicationRotationFollowingControllerView: SourceryGeneration {}
extension UIKit.UIControl: SourceryGeneration {}
extension UIKit._MKRightImageButton: SourceryGeneration {}
extension UIKit._MKSmallCalloutPassthroughButton: SourceryGeneration {}
extension UIKit.CNPostalAddressEditorView: SourceryGeneration {}
extension UIKit.CNContactPhotoView: SourceryGeneration {}
extension UIKit._UIActionSlider: SourceryGeneration {}
extension UIKit._UISearchDisplayControllerDimmingView: SourceryGeneration {}
extension UIKit._UITableViewCellDeleteConfirmationControl_Legacy: SourceryGeneration {}
extension UIKit._UIButtonBarButton: SourceryGeneration {}
extension UIKit._UITableViewCellGrabber: SourceryGeneration {}
extension UIKit.UIPrinterSetupPINView: SourceryGeneration {}
extension UIKit.UIInputSwitcherSegmentControl: SourceryGeneration {}
extension UIKit.UIRefreshControl: SourceryGeneration {}
extension UIKit.UITabBarButton: SourceryGeneration {}
extension UIKit.UIStepper: SourceryGeneration {}
extension UIKit.UIIndexBarView: SourceryGeneration {}
extension UIKit.UIIndexBarAccessoryView: SourceryGeneration {}
extension UIKit.UITableViewCellReorderControl: SourceryGeneration {}
extension UIKit.UITableViewCellFocusableReorderControl: SourceryGeneration {}
extension UIKit.UITableViewCellDeleteConfirmationControl_Legacy: SourceryGeneration {}
extension UIKit.UITableViewCellEditControl: SourceryGeneration {}
extension UIKit.UITableViewCellFocusableEditControl: SourceryGeneration {}
extension UIKit.UIMovieScrubber: SourceryGeneration {}
extension UIKit.UITableViewIndex: SourceryGeneration {}
extension UIKit.UIDatePicker: SourceryGeneration {}
extension UIKit.UISwitch: SourceryGeneration {}
extension UIKit.UIDebuggingSwitch: SourceryGeneration {}
extension UIKit.UITableViewCellDetailDisclosureView: SourceryGeneration {}
extension UIKit.UIPageControl: SourceryGeneration {}
extension UIKit.UICoverSheetButton: SourceryGeneration {}
extension UIKit.UIToolbarButton: SourceryGeneration {}
extension UIKit.UIToolbarTextButton: SourceryGeneration {}
extension UIKit.UICalloutView: SourceryGeneration {}
extension UIKit.UITextField: SourceryGeneration {}
extension UIKit._UIAlertControllerTextField: SourceryGeneration {}
extension UIKit.UIDocumentPasswordField: SourceryGeneration {}
extension UIKit.UISearchBarTextField: SourceryGeneration {}
extension UIKit.UISearchField: SourceryGeneration {}
extension UIKit.UISlider: SourceryGeneration {}
extension UIKit._UIDynamicSlider: SourceryGeneration {}
extension UIKit.UIRemoveControlTextButton: SourceryGeneration {}
extension UIKit.UIRemoveControlMinusButton: SourceryGeneration {}
extension UIKit.UIRemoveControlMultiSelectButton: SourceryGeneration {}
extension UIKit.UISegmentedControl: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateBarSegmentControl: SourceryGeneration {}
extension UIKit.UIButton: SourceryGeneration {}
extension UIKit.MKPlaceHeaderButton: SourceryGeneration {}
extension UIKit.MKButtonWithTargetArgument: SourceryGeneration {}
extension UIKit.MKPlaceAttributionCellButton: SourceryGeneration {}
extension UIKit._MKUserTrackingButton: SourceryGeneration {}
extension UIKit.CNTransportButton: SourceryGeneration {}
extension UIKit.CNStarkKnobTransportButton: SourceryGeneration {}
extension UIKit.CNPropertyLabelButton: SourceryGeneration {}
extension UIKit._UIModernBarButton: SourceryGeneration {}
extension UIKit._UIStatusBarSystemNavigationItemButton: SourceryGeneration {}
extension UIKit._UIStepperButton: SourceryGeneration {}
extension UIKit._UIShortPlacardButton: SourceryGeneration {}
extension UIKit._UIPlacardButton: SourceryGeneration {}
extension UIKit._UITableViewCellActionButton: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateToggleButton: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateInlineFloatingToggleButton: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateSplitKeyboardToggleButton: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateUnsplitKeyboardToggleButton: SourceryGeneration {}
extension UIKit.UIKeyboardButton: SourceryGeneration {}
extension UIKit.UIKeyboardDictationStarkDoneButton: SourceryGeneration {}
extension UIKit.UIKeyboardDockItemButton: SourceryGeneration {}
extension UIKit.UISwipeActionButton: SourceryGeneration {}
extension UIKit.UISwipeActionStandardButton: SourceryGeneration {}
extension UIKit.UISwipeActionCircularButton: SourceryGeneration {}
extension UIKit.UICalloutBarButton: SourceryGeneration {}
extension UIKit.UIStatusBarCarPlayDockAppItemButton: SourceryGeneration {}
extension UIKit.UIPopoverButton: SourceryGeneration {}
extension UIKit.UITexturedButton: SourceryGeneration {}
extension UIKit.UIRoundedRectButton: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateLogButton: SourceryGeneration {}
extension UIKit.UISegmentAccessibilityButton: SourceryGeneration {}
extension UIKit.UINavigationButton: SourceryGeneration {}
extension UIKit._UIToolbarNavigationButton: SourceryGeneration {}
extension UIKit.UIKBEmojiSnapshotSizingView: SourceryGeneration {}
extension UIKit.UIScrollView: SourceryGeneration {}
extension UIKit._MKPlacePhotoView: SourceryGeneration {}
extension UIKit.NUIContentScrollView: SourceryGeneration {}
extension UIKit._UIInterfaceActionRepresentationsSequenceView: SourceryGeneration {}
extension UIKit._UIQueuingScrollView: SourceryGeneration {}
extension UIKit._UIAlertControllerShadowedScrollView: SourceryGeneration {}
extension UIKit._UIInterfaceActionGroupHeaderScrollView: SourceryGeneration {}
extension UIKit._UICompatibilityTextView: SourceryGeneration {}
extension UIKit.UIPrinterSetupPINScrollView: SourceryGeneration {}
extension UIKit.UITextView: SourceryGeneration {}
extension UIKit._UISiriTranscriptTextView: SourceryGeneration {}
extension UIKit.UIWebOverflowScrollView: SourceryGeneration {}
extension UIKit.UIPageControllerScrollView: SourceryGeneration {}
extension UIKit.UIWebScrollView: SourceryGeneration {}
extension UIKit._UIWebViewScrollView: SourceryGeneration {}
extension UIKit.UIFieldEditor: SourceryGeneration {}
extension UIKit.UITableView: SourceryGeneration {}
extension UIKit.CNAvatarCardActionsTableView: SourceryGeneration {}
extension UIKit.CNContactListTableView: SourceryGeneration {}
extension UIKit.CNPostalAddressEditorTableView: SourceryGeneration {}
extension UIKit.CNUINavigationListView: SourceryGeneration {}
extension UIKit.CNMaskingTableView: SourceryGeneration {}
extension UIKit.CNContactView: SourceryGeneration {}
extension UIKit._UIMoreListTableView: SourceryGeneration {}
extension UIKit.UIInputSwitcherTableView: SourceryGeneration {}
extension UIKit.UIPickerTableView: SourceryGeneration {}
extension UIKit.UISearchResultsTableView: SourceryGeneration {}
extension UIKit.UITableViewWrapperView: SourceryGeneration {}
extension UIKit.UICollectionView: SourceryGeneration {}
extension UIKit.MKVenuesBrowseCollectionView: SourceryGeneration {}
extension UIKit.CNUIPeopleGroupsGridView: SourceryGeneration {}
extension UIKit.UIKBCandidateCollectionView: SourceryGeneration {}
extension UIKit.UIKeyboardCandidateGridCollectionView: SourceryGeneration {}
extension UIKit.UIKeyboardEmojiCollectionView: SourceryGeneration {}
extension UIKit.UIKBKeyView: SourceryGeneration {}
extension UIKit.UIKBContainerKeyView: SourceryGeneration {}
extension UIKit.UIKBFloatingKeyView: SourceryGeneration {}
extension UIKit.UIKBBlurredKeyView: SourceryGeneration {}
extension UIKit.UIKBCandidateView: SourceryGeneration {}
extension UIKit.UIKBHandwritingView: SourceryGeneration {}
extension UIKit.UIKBDictationDisplayView: SourceryGeneration {}
extension UIKit.UIKBRecentInputsView: SourceryGeneration {}
extension UIKit.UIKBHandwritingCandidateView: SourceryGeneration {}
extension UIKit.UIKBLinearCandidateView: SourceryGeneration {}
extension UIKit.UIKeyboardEmojiKeyView: SourceryGeneration {}
extension UIKit.UIKeyboardEmojiSplit: SourceryGeneration {}
extension UIKit.UIKeyboardEmojiSplitCategoryPicker: SourceryGeneration {}
extension UIKit.UIKeyboardEmojiCategoryBar: SourceryGeneration {}
extension UIKit.UIKeyboardEmojiCategoryBar_iPad: SourceryGeneration {}
extension UIKit.UIKeyboardEmojiCategoryBar_iPhone: SourceryGeneration {}
extension UIKit.UIKeyboardEmojiCollectionInputView: SourceryGeneration {}
extension UIKit.UIKeyboardEmojiSplitCharacterPicker: SourceryGeneration {}
extension UIKit.UIPickerView: SourceryGeneration {}
extension UIKit._UIDatePickerView: SourceryGeneration {}
extension UIKit.UIPrintRangePickerView: SourceryGeneration {}
extension UIKit.UIWebSelectMultiplePicker: SourceryGeneration {}
extension UIKit.UIWebSelectSinglePicker: SourceryGeneration {}


